# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/user/Desktop/JoltyGym

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/user/Desktop/JoltyGym

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"python\" \"tinyxml2_development\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/Desktop/JoltyGym/CMakeFiles /Users/user/Desktop/JoltyGym//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/user/Desktop/JoltyGym/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named Jolt

# Build rule for target.
Jolt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Jolt
.PHONY : Jolt

# fast build rule for target.
Jolt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/joltphysics-build/CMakeFiles/Jolt.dir/build.make _deps/joltphysics-build/CMakeFiles/Jolt.dir/build
.PHONY : Jolt/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/Experimental.dir/build.make _deps/tinyxml2-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/Nightly.dir/build.make _deps/tinyxml2-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/Continuous.dir/build.make _deps/tinyxml2-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyStart.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyBuild.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyTest.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/NightlySubmit.dir/build.make _deps/tinyxml2-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/tinyxml2-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousStart.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousTest.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/tinyxml2-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named tinyxml2

# Build rule for target.
tinyxml2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyxml2
.PHONY : tinyxml2

# fast build rule for target.
tinyxml2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/tinyxml2-build/CMakeFiles/tinyxml2.dir/build.make _deps/tinyxml2-build/CMakeFiles/tinyxml2.dir/build
.PHONY : tinyxml2/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named vk-bootstrap

# Build rule for target.
vk-bootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vk-bootstrap
.PHONY : vk-bootstrap

# fast build rule for target.
vk-bootstrap/fast:
	$(MAKE) $(MAKESILENT) -f _deps/vk-bootstrap-build/CMakeFiles/vk-bootstrap.dir/build.make _deps/vk-bootstrap-build/CMakeFiles/vk-bootstrap.dir/build
.PHONY : vk-bootstrap/fast

#=============================================================================
# Target rules for targets named joltgym_core

# Build rule for target.
joltgym_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joltgym_core
.PHONY : joltgym_core

# fast build rule for target.
joltgym_core/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/joltgym_core.dir/build.make src/core/CMakeFiles/joltgym_core.dir/build
.PHONY : joltgym_core/fast

#=============================================================================
# Target rules for targets named joltgym_mjcf

# Build rule for target.
joltgym_mjcf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joltgym_mjcf
.PHONY : joltgym_mjcf

# fast build rule for target.
joltgym_mjcf/fast:
	$(MAKE) $(MAKESILENT) -f src/mjcf/CMakeFiles/joltgym_mjcf.dir/build.make src/mjcf/CMakeFiles/joltgym_mjcf.dir/build
.PHONY : joltgym_mjcf/fast

#=============================================================================
# Target rules for targets named compile_shaders

# Build rule for target.
compile_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_shaders
.PHONY : compile_shaders

# fast build rule for target.
compile_shaders/fast:
	$(MAKE) $(MAKESILENT) -f src/shaders/CMakeFiles/compile_shaders.dir/build.make src/shaders/CMakeFiles/compile_shaders.dir/build
.PHONY : compile_shaders/fast

#=============================================================================
# Target rules for targets named joltgym_renderer

# Build rule for target.
joltgym_renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joltgym_renderer
.PHONY : joltgym_renderer

# fast build rule for target.
joltgym_renderer/fast:
	$(MAKE) $(MAKESILENT) -f src/renderer/CMakeFiles/joltgym_renderer.dir/build.make src/renderer/CMakeFiles/joltgym_renderer.dir/build
.PHONY : joltgym_renderer/fast

#=============================================================================
# Target rules for targets named joltgym_native

# Build rule for target.
joltgym_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joltgym_native
.PHONY : joltgym_native

# fast build rule for target.
joltgym_native/fast:
	$(MAKE) $(MAKESILENT) -f src/bindings/CMakeFiles/joltgym_native.dir/build.make src/bindings/CMakeFiles/joltgym_native.dir/build
.PHONY : joltgym_native/fast

_deps/imgui-src/backends/imgui_impl_sdl2.o: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdl2.i: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdl2.s: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s

_deps/imgui-src/backends/imgui_impl_vulkan.o: _deps/imgui-src/backends/imgui_impl_vulkan.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_vulkan.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.cpp.o

_deps/imgui-src/backends/imgui_impl_vulkan.i: _deps/imgui-src/backends/imgui_impl_vulkan.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_vulkan.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.cpp.i

_deps/imgui-src/backends/imgui_impl_vulkan.s: _deps/imgui-src/backends/imgui_impl_vulkan.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_vulkan.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_vulkan.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... compile_shaders"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... Jolt"
	@echo "... SDL2-static"
	@echo "... SDL2main"
	@echo "... imgui"
	@echo "... joltgym_core"
	@echo "... joltgym_mjcf"
	@echo "... joltgym_native"
	@echo "... joltgym_renderer"
	@echo "... tinyxml2"
	@echo "... vk-bootstrap"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_vulkan.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_vulkan.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_vulkan.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

